apiVersion: v1
kind: Secret
metadata:
  name: zdrive-secrets
  namespace: zdrive
type: Opaque
stringData:
  postgres-user: zdrive
  postgres-password: zdrive_password
  jwt-secret: your-secret-jwt-key-change-in-production
  rabbitmq-user: zdrive
  rabbitmq-password: zdrive_password

